# Change these first
owner: joahn3 # Your GitHub organization or username, where this repository lives
repo: earthlink-uptime # The name of this repository
user-agent: joahn3

sites:
  - name: EarthLink
    url: https://www.earthlink.ro
    icon: https://earthlink.ro/favico.png
  - name: RolCris
    url: https://rolcris.ro
    icon: https://www.rolcris.ro/favicons/favicon.ico
  - name: CEI Sales
    url: https://ceisales.com
    icon: https://ceisales.com/favicons/favicon.ico
  - name: Secom
    url: https://www.secom.ro
    icon: https://www.secom.ro/img/frontend/secom-logo.svg
  - name: Mega Construct
    url: https://www.megaconstruct.ro/
    icon: https://www.megaconstruct.ro/wp-content/uploads/2016/06/final-logo.jpg
  - name: BLT
    url: https://www.blt.ro
    icon: https://www.blt.ro/_res/media/media-generala/favicon-blt3.png
  - name: MIBA
    url: https://www.miba.ro
    icon: https://www.miba.ro/img/logo.png
  - name: TCC Iasi
    url: https://www.tcc-iasi.ro
    icon: https://www.tcc-iasi.ro/images/logo.png
  - name: Felix Telecom
    url: https://www.felixtelecom.ro
    icon: https://www.felixtelecom.ro/assets/img/svg/logo-intreg.svg
  - name: Paicu & Sons Consulting
    url: https://paicucons.ro
    icon: https://paicucons.ro/wp-content/themes/paicu/inc/assets/images/logo-dark.png
  - name: Amoobi
    url: https://www.amoobi.com
    icon: https://www.amoobi.com/files/design/logo_amoobi.png
  - name: GlobStar 1
    url: https://www.globstar.ro/
    icon: https://www.globstar.ro/img/dor-bionic-logo-1574507922.jpg
  - name: Ted Electric EU
    url: https://www.tedelectric.eu/
    icon: https://www.tedelectric.eu/lay/ted-top/ted_top_r1_c1.png
  

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /earthlink-uptime
  name: 
  logoUrl: https://earthlink.ro/images/logos/logo.png
  introTitle: "**Earthlink** monitor and status page."
  introMessage: It uses **real-time** data from our [GitHub repository](https://github.com/joahn3/earthlink-uptime).
  navbar:
    - title: Earthlink
      href: https://earthlink.ro

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
